# отключить предупреждения Python, если они мешают
ignore_warnings: False

# запросить теги у пользователя, если они не указаны в конфиге
enforce_tags: True

# красиво вывести дерево конфига в начале запуска через Rich
print_config: True
