_target_: src.models.detection_module.DetectionLitModel

_recursive_: false

defaults:
  - components: base_model
  - optimizer: adam
  - scheduler: chaincyclic

# compile model for faster training with pytorch 2.0
compile: false

iou_thresh: 0.5

loss_weights:
  _target_: src.models.components.losses.DetectionLoss
  loss_weights:
    loss_classifier: 1.0
    loss_box_reg: 1.0
    loss_objectness: 1.0
    loss_rpn_box_reg: 1.0
