_target_: src.models.detection_module.DetectionLitModel

_recursive_: false

defaults:
  - components: base_model
  - optimizer: adam
  - scheduler: chaincyclic

# compile model for faster training with pytorch 2.0
compile: false

iou_thresh: 0.5
