# путь к корневой директории
# требуется переменная окружения PROJECT_ROOT
# можно заменить на ".", если корнем должна быть текущая рабочая директория
root_dir: ${oc.env:PROJECT_ROOT}

# путь к директории с данными
data_dir: ${paths.root_dir}/data/

# путь к директории логов
log_dir: ${paths.root_dir}/logs/

# путь к выходной директории, создаваемой Hydra динамически
# шаблон пути задан в `configs/hydra/default.yaml`
# используется для файлов, созданных во время запуска: чекпоинтов, метрик и т.д.
output_dir: ${hydra:runtime.output_dir}

# путь к рабочей директории
work_dir: ${hydra:runtime.cwd}
