# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ??? # отслеживаемая величина, обязательно указать
  min_delta: 0. # минимальное изменение отслеживаемой величины, считающееся улучшением
  patience: 3 # число проверок без улучшения, после которого обучение будет остановлено
  verbose: False # режим подробного вывода
  mode: "min" # "max" означает, что большее значение метрики лучше; также доступен "min"
  strict: True # падать с ошибкой, если monitor не найден в валидационных метриках
  check_finite: True # если True, останавливает обучение при NaN или бесконечном значении monitor
  stopping_threshold: null # остановить обучение сразу при достижении этого порога
  divergence_threshold: null # остановить обучение, как только метрика станет хуже этого порога
  check_on_train_epoch_end: null # запускать early stopping в конце эпохи обучения
  # log_rank_zero_only: False  # этот аргумент недоступен в стабильной версии
