# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: null # директория для сохранения файла модели
  filename: null # имя файла чекпоинта
  monitor: null # имя логируемой метрики, по которой определяется улучшение модели
  verbose: False # режим подробного вывода
  save_last: null # дополнительно всегда сохранять последнюю точную копию чекпоинта в last.ckpt
  save_top_k: 1 # сохранять k лучших моделей по указанной выше метрике
  mode: "min" # "max" означает, что большее значение метрики лучше; также доступен "min"
  auto_insert_metric_name: True # если True, имя метрики добавляется в имена файлов чекпоинтов
  save_weights_only: False # если True, сохраняются только веса модели
  every_n_train_steps: null # число шагов обучения между сохранениями чекпоинтов
  train_time_interval: null # сохранять чекпоинты с указанным временным интервалом
  every_n_epochs: null # число эпох между сохранениями чекпоинтов
  save_on_train_epoch_end: null # сохранять чекпоинт в конце эпохи обучения или в конце валидации
