# @package _global_

defaults:
  - _self_
  - data: cs_datamodule # выберите датамодуль с `test_dataloader()` для оценки
  - model: base_det
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# передача пути контрольной точки необходима для оценки
ckpt_path: ???
