# @package _global_

# базовая настройка отладки, запускает 1 полную эпоху
# другие отладочные конфиги могут наследоваться от этого

# переопределяем имя задачи, чтобы отладочные логи сохранялись отдельно
task_name: "debug"

# отключаем callback-и и логгеры во время отладки
callbacks: null
logger: null

extras:
  ignore_warnings: False
  enforce_tags: False

# устанавливает уровень всех консольных логгеров в 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra:
  job_logging:
    root:
      level: DEBUG

  # используйте это, чтобы также перевести логгеры Hydra в 'DEBUG'
  # verbose: True

trainer:
  max_epochs: 1
  accelerator: cpu # отладчики плохо работают с GPU
  devices: 1 # отладчики плохо работают с multiprocessing
  enable_checkpointing: false # не перезагружать отладочные чекпоинты в PyTorch 2.6+
  detect_anomaly: true # бросать исключение, если в тензорах найден NaN или +/-inf

data:
  num_workers: 0 # отладчики плохо работают с multiprocessing
  pin_memory: False # отключить закрепление памяти для GPU
  persistent_workers: False # отладчики плохо работают с multiprocessing
