# @package _global_

# переобучение на 3 батчах

defaults:
  - default

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: 1
  overfit_batches: 3

data:
  augmentations: none

# во время overfit-режима нужно отключить чекпоинты модели и early stopping
callbacks: null
