# @package _global_

# overfits to 3 batches

defaults:
  - default

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: 1
  overfit_batches: 3

data:
  augmentations: none

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
